[tool.autopep8]
max_line_length = 120

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]

build-backend = "setuptools.build_meta"

[project]
name = "scrapeai"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["src"]